version: '3.8'

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - /home/fangqq/myproject/zookeeper/data:/data
      - /home/fangqq/myproject/zookeeper/datalog:/datalog
    healthcheck:
      test: [ "CMD", "zkServer.sh", "status" ]   # 更可靠的健康检查
      interval: 30s
      timeout: 10s
      retries: 3

  gateway:
    image: gateway:latest
    container_name: gateway
    restart: always
    ports:
      - "10080:10080"
    environment:
      - SPRING_ZOOKEEPER_CONNECT=zookeeper
    depends_on:
      - zookeeper

  flowengine:
    image: flowengine-1.0:latest
    container_name: flowengine
    restart: always
    ports:
      - "10085:10085"
    volumes:
      - /home/fangqq/myproject/flowengine/data:/home/fqq/myproject/flowengine/data   # 容器内路径建议用简短的绝对路径
    environment:
      - SPRING_ZOOKEEPER_CONNECT=zookeeper
    depends_on:
      - zookeeper